

// js/localization.js

const translations = {
    'en': {
        'Canteen Admin': 'Canteen Admin',
        'Admin Panel': 'Admin Panel',
        'Publish Menu': 'Publish Menu',
        'Start Date': 'Start Date',
        'End Date': 'End Date',
        'Menu Items (JSON format)': 'Menu Items (JSON format)',
        'Publish': 'Publish',
        'Incoming Orders': 'Incoming Orders',
        'Order ID': 'Order ID',
        'Status': 'Status',
        'Total': 'Total',
        'Items': 'Items',
        'Mark Ready': 'Mark Ready',
        'Mark Picked Up': 'Mark Picked Up',
        'Your cart is empty!': 'Your cart is empty!',
        'Order placed successfully!': 'Order placed successfully!',
        'Failed to place order. Please try again.': 'Failed to place order. Please try again.',
        'No menu available for today.': 'No menu available for today.',
        'Error loading menu. Please try again later.': 'Error loading menu. Please try again later.',
        'No items match your filter criteria.': 'No items match your filter criteria.',
        'Today\'s Menu': 'Today\'s Menu',
        'Filters': 'Filters',
        'Gluten-Free': 'Gluten-Free',
        'Dairy-Free': 'Dairy-Free',
        'Vegetarian': 'Vegetarian',
        'Vegan': 'Vegan',
        'Nutrition Planner': 'Nutrition Planner',
        'Gender': 'Gender',
        'Male': 'Male',
        'Female': 'Female',
        'Weight (kg)': 'Weight (kg)',
        'Height (cm)': 'Height (cm)',
        'Age': 'Age',
        'Activity Level': 'Activity Level',
        'Sedentary': 'Sedentary',
        'Lightly Active': 'Lightly Active',
        'Moderately Active': 'Moderately Active',
        'Very Active': 'Very Active',
        'Extremely Active': 'Extremely Active',
        'Calculate Macros': 'Calculate Macros',
        'Your Daily Macro Targets:': 'Your Daily Macro Targets:',
        'Calories': 'Calories',
        'Protein': 'Protein',
        'Carbs': 'Carbs',
        'Fat': 'Fat',
        'Cart': 'Cart',
        'No items in cart.': 'No items in cart.',
        'Cart Summary:': 'Cart Summary:',
        'Total Items:': 'Total Items:',
        'Total Price:': 'Total Price:',
        'Total Calories:': 'Total Calories:',
        'Total Protein:': 'Total Protein:',
        'Total Carbs:': 'Total Carbs:',
        'Total Fat:': 'Total Fat:',
        'Place Order': 'Place Order',
        'Add to Cart': 'Add to Cart'
    },
    'tr': {
        'Canteen Admin': 'Kantin Yönetimi',
        'Admin Panel': 'Yönetici Paneli',
        'Publish Menu': 'Menü Yayınla',
        'Start Date': 'Başlangıç Tarihi',
        'End Date': 'Bitiş Tarihi',
        'Menu Items (JSON format)': 'Menü Öğeleri (JSON formatı)',
        'Publish': 'Yayınla',
        'Incoming Orders': 'Gelen Siparişler',
        'Order ID': 'Sipariş No',
        'Status': 'Durum',
        'Total': 'Toplam',
        'Items': 'Öğeler',
        'Mark Ready': 'Hazır Olarak İşaretle',
        'Mark Picked Up': 'Teslim Edildi Olarak İşaretle',
        'Your cart is empty!': 'Sepetiniz boş!',
        'Order placed successfully!': 'Sipariş başarıyla verildi!',
        'Failed to place order. Please try again.': 'Sipariş verilemedi. Lütfen tekrar deneyin.',
        'No menu available for today.': 'Bugün için menü mevcut değil.',
        'Error loading menu. Please try again later.': 'Menü yüklenirken hata oluştu. Lütfen daha sonra tekrar deneyin.',
        'No items match your filter criteria.': 'Filtreleme kriterlerinize uyan öğe bulunamadı.',
        'Today\'s Menu': 'Bugünün Menüsü',
        'Filters': 'Filtreler',
        'Gluten-Free': 'Glutensiz',
        'Dairy-Free': 'Laktozsuz',
        'Vegetarian': 'Vejetaryen',
        'Vegan': 'Vegan',
        'Nutrition Planner': 'Beslenme Planlayıcı',
        'Gender': 'Cinsiyet',
        'Male': 'Erkek',
        'Female': 'Kadın',
        'Weight (kg)': 'Kilo (kg)',
        'Height (cm)': 'Boy (cm)',
        'Age': 'Yaş',
        'Activity Level': 'Aktivite Seviyesi',
        'Sedentary': 'Hareketsiz',
        'Lightly Active': 'Az Aktif',
        'Moderately Active': 'Orta Derece Aktif',
        'Very Active': 'Çok Aktif',
        'Extremely Active': 'Aşırı Aktif',
        'Calculate Macros': 'Makroları Hesapla',
        'Your Daily Macro Targets:': 'Günlük Makro Hedefleriniz:',
        'Calories': 'Kalori',
        'Protein': 'Protein',
        'Carbs': 'Karbonhidrat',
        'Fat': 'Yağ',
        'Cart': 'Sepet',
        'No items in cart.': 'Sepette ürün yok.',
        'Cart Summary:': 'Sepet Özeti:',
        'Total Items:': 'Toplam Ürün:',
        'Total Price:': 'Toplam Fiyat:',
        'Total Calories:': 'Toplam Kalori:',
        'Total Protein:': 'Toplam Protein:',
        'Total Carbs:': 'Toplam Karbonhidrat:',
        'Total Fat:': 'Toplam Yağ:',
        'Place Order': 'Sipariş Ver',
        'Add to Cart': 'Sepete Ekle'
    }
};

export function setLanguage(lang) {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    // Update title separately as it\'s not a data-lang attribute
    if (translations[lang] && translations[lang][document.title]) {
        document.title = translations[lang][document.title];
    }
}
